# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03d80de3508fdb404b43692cc0b4fb7d51cbb4853eba6e6bd821ee1325de9afb3d91005af2bb1bacd5aad71db4c27967ff90b5230e20f97e9718a622198f26f6

test:
  secret_key_base: 9edb3fedd7f60c8676ce8d2d2626433498e1b1b642559987fff85b6875201c2c80bc909c2f8163ced1ca7ab06446bb760cc1b095a31b7697455164a7da8d5b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
